<?php

namespace AppBundle\Repository;

use Doctrine\ORM\AbstractQuery;

/**
 * AsteroidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsteroidRepository extends \Doctrine\ORM\EntityRepository
{
    public function findHazardous($isHazardous = false)
    {
        $qb = $this->createQueryBuilder('a');

        return $qb->where('a.isHazardous =:isHazardous')
            ->setParameter('isHazardous', $isHazardous)
            ->getQuery()
            ->getArrayResult();
    }

    public function findFastedAsteroid($isHazardous = false)
    {
        $qb = $this->createQueryBuilder('a');

        $maxSpeed = $qb
            ->select('MAX(a.speed)')
            ->where('a.isHazardous =:isHazardous')
            ->setParameter('isHazardous', $isHazardous)
            ->getQuery()
            ->getSingleScalarResult();

        return $this->createQueryBuilder('a')
            ->where('a.speed =:speed')
            ->setParameter('speed', $maxSpeed)
            ->getQuery()
            ->getOneOrNullResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
